### ISSUE TITLE
when Player Transition to AS, the Lobby takes a long time to remove the player from the room 

### ISSUE THREAD

**Issue by Zackmon** [Zackmon/FragmentServer_netCore#10]
when Player Transition to AS, the Lobby takes a long time to remove the player from the room 

need to check the OPCode for entering AS

**Comment by formlesstree4** [comment]
Is there an opcode for this?

**Comment by formlesstree4** [comment]
So there's not an opcode for actually transferring to the area server. The only way to probably lower the TTL would be to decrease the "keep-alive" or ping in the client.

**Comment by Zackmon** [comment]
this is the best we can do for now
