### ISSUE TITLE
Refactoring OpCode Handling

### ISSUE THREAD

**Issue by formlesstree4** [Zackmon/FragmentServer_netCore#19]
I've titled it a refactor but this is meant to capitalize on redoing how opcodes in general are processed.

Right now, `GameClientAsync` is solely responsible for the managing and handling of opcodes. This is less than ideal and means that `GameClientAsync` remains as this sort of [God object](https://en.wikipedia.org/wiki/God_object). This will eventually become a nightmare to extend and handle debugging. Plus, if we get more than two people working in this codebase, merge conflicts will suck. So the purpose of this issue is to provide a way to document and track the overall migration efforts to a new system.

I know @Zackmon has started doing a bit of a demonstration on how this would look. I'm working on one now inside a separate branch on my forked repo that will follow something like this:

# Packet Handling
For starters, there will be several newly defined classes:
1. IOpCodeProviderService
2. IOpCodeHandler
3. RequestContent
4. ResponseContent
5. OpCodeAttribute
6. OpCodeDataAttribute

## IOpCodeProviderService
This service is responsible for the dynamic discovery and mapping of `IOpCodeHandler` instances. In addition, it will include reportable information, such as available OpCodes, and some reporting statistics.

```cs
    /// <summary>
    /// A service provider that's responsible for the discovery and management of the various <see cref="IOpCodeHandler"/> instances
    /// </summary>
    public interface IOpCodeProviderService
    {

        /// <summary>
        /// Gets a collection of <see cref="IOpCodeHandler"/>s but as their defined type
        /// </summary>
        IReadOnlyCollection<Type> Handlers { get; }

        /// <summary>
        /// Handles processing the incoming <see cref="PacketAsync"/>
        /// </summary>
        /// <param name="gameClient">The <see cref="GameClientAsync"/> that submitted the request</param>
        /// <param name="packet">The <see cref="PacketAsync"/> to handle</param>
        Task<ResponseContent> HandlePacketAsync(GameClientAsync gameClient, PacketAsync packet);

    }
```

## IOpCodeHandler
One or more OpCodes will be handled by an implementation of `IOpCodeHandler`. A `RequestContent` object comes into it and a `ResponseContent` object will be returned. The classes are all assuming async/await behavior by default and the interfaces have been designed accordingly.

```cs
    /// <summary>
    /// Defines a lightweight interface who is responsible for handling incoming packet requests
    /// </summary>
    public interface IOpCodeHandler
    {

        /// <summary>
        /// Handles the incoming <see cref="PacketAsync"/> instance
        /// </summary>
        /// <param name="request">The incoming <see cref="RequestContent"/></param>
        /// <returns>A promise to handle the packet asynchronously</returns>
        Task<ResponseContent> HandleIncomingRequestAsync(RequestContent request);

    }
```

## RequestContent
A small wrapper that deconstructs the incoming request down into the OpCode, Data Packet, and Client that is being processed.

```cs
    /// <summary>
    /// Defines a particular request that was sent via a connected client
    /// </summary>
    public sealed class RequestContent
    {

        /// <summary>
        /// Gets the <see cref="GameClientAsync"/> that has submitted this request
        /// </summary>
        public GameClientAsync Client { get; private set; }

        /// <summary>
        /// Gets the OpCode that was submitted by the <see cref="Client"/>
        /// </summary>
        public ushort OpCode { get; private set; }

        /// <summary>
        /// Gets the optional Data OpCode that was submitted by the <see cref="Client"/>
        /// </summary>
        /// <remarks>
        /// If <see cref="OpCode"/> does not equal <see cref="OpCodes.OPCODE_DATA"/> (or 0x30) then this will be NULL
        /// </remarks>
        public ushort? DataOpCode { get; private set; }

        /// <summary>
        /// Gets the data payload that was submitted by the <see cref="Client"/>
        /// </summary>
        public byte[] Data { get; private set; }

}

```

## ResponseContent
A small wrapper that contains all the necessary information to submit data back to the Client.

```cs
    /// <summary>
    /// Defines the response object for a particular request
    /// </summary>
    public sealed class ResponseContent
    {

        /// <summary>
        /// Gets the <see cref="RequestContent"/> that generated this <see cref="ResponseContent"/>
        /// </summary>
        public RequestContent Request { get; }

        /// <summary>
        /// Gets the responding OpCode
        /// </summary>
        public ushort OpCode { get; private set; }

        /// <summary>
        /// Gets the responding byte array of content
        /// </summary>
        public byte[] Data { get; private set; }

        /// <summary>
        /// Gets the responding checksum
        /// </summary>
        /// <remarks>
        /// If Checksum is NULL, the response type is ASSUMED to be a Data Packet response (meaning the <see cref="RequestContent"/> OpCode was <see cref="OpCodes.OPCODE_DATA"/>)
        /// </remarks>
        public uint? Checksum { get; private set; }

}

```

Things like proper encryption / decryption are to be handled automatically. For example, `PacketAsync` already handles properly decrypting the incoming data. The assumption would be that `ResponseContent` would handle encrypting the payload (including checksum calculation) since the `RequestContent` class includes the Client, therefore exposing the necessary encryption keys.

This also means that each implementation of `IOpCodeHandler` can narrow their access scope to only classes they need to care about. Additionally, it is assumed that `IOpCodeHandler` instances will be created on-the-fly via Dependency Injection, removing any worry or concern about shared resources (provided implementations and dependencies in the class itself behave).

@Zackmon feel free to assign this to me.

**Comment by formlesstree4** [comment]
A slight deviation from the technical design:

A handler can return zero or more `ResponseContent` objects to be sent in sequential order. A handful of OpCodes need the capability to submit several packets of data at a time. As such, the system needs to be flexible enough to handle such an adjustment.

**Comment by formlesstree4** [comment]
I think we can close this now. @Zackmon ?

**Comment by Zackmon** [comment]
@formlesstree4 yes

thank you for your awesome support
