### ISSUE TITLE
If multiple people buy the same item from a guild shop at the same time, the item amount underflows

### ISSUE THREAD

**Issue by unnamedau** [Zackmon/FragmentServer_netCore#22]
If x amount of an item is an a guild shop, and multiple people all try to buy the entire stock, or enough to combined be greater than x, the server will give all players the amount they asked for, and the shop's amount of that item will underflow around to 65535.
While I'm not sure there's a way around everyone getting the items, which opens the possibility of guild shop item duplication, this feels like something that should be relatively™ easy to fix.
![image](https://user-images.githubusercontent.com/29384539/132780232-bf808770-811d-44e1-aa3f-e51cc721d8bd.png)

**Comment by formlesstree4** [comment]
I believe this is fixed in [this](https://github.com/Zackmon/FragmentServer_netCore/pull/23/commits/2b2e356ae741d278a13a77eff247e2427192b99f) commit.

**Comment by formlesstree4** [comment]
@Zackmon Can we close this out now?

**Comment by Zackmon** [comment]
@formlesstree4 
I think so , haven’t heard any issues regarding this recently 

@unnamedau can you please ping me if this ever get brought up again ?
