### ISSUE TITLE
Player avatar in the lobby shows incorrectly

### ISSUE THREAD

**Issue by unnamedau** [Zackmon/FragmentServer_netCore#8]
Pulling up an online player's profile in the lobby causes their icon to show as a shrunken-down version of the current screen(using the lobbychat can cause the text to show in the profile icon)

![unknown-50](https://user-images.githubusercontent.com/29384539/108834138-06356a80-758b-11eb-84fb-5ade23bcfebc.png)

**Comment by Zackmon** [comment]
fixed by Alice in .hack//frägment Definitive Translation v3.0
